### ISSUE TITLE
Better table formatting

### ISSUE THREAD

**Issue by Entomy** [Entomy/Stringier#24]
It would be useful for many console projects (and maybe others) to have a better option for tabular formatting than through [`String.Format()`](https://docs.microsoft.com/en-us/dotnet/api/system.string.format), which is quite limited.

Notably, it should be able to understand table headers and footers, optionally center text rather than just left or right align, and automatically adjust width based on column maximums.

**Comment by HugoRoss** [comment]
It's not exactly what you are looking for, but I've written an extension method that does the `String.Format(..)` functionality in a safe way and you may have it if you are interested in. Formats like `"{0}{1}{2}"` make a single call to the standard implementation, but everything that `String.Format(..)` cannot process directly is parsed into literals and placeholders and then `String.Format(..)` is called separately on each parameter, enabling format strings like `"{1}"` (unused arguments, which is pretty cool in translations, e.g. `"The temperature is {1:0.#}°F.".FillIn(degreesC, degreesF)`), and any fancy format string like `"}{  {0}{1}-{{2}{3}{4}}-{5}{6}{7}".FillIn(0, 1, 2, 3, 4, 5, 6, 7)` just works and returns `"}{  01-{234}-567"` without complaining. A center functionality could easily be added, e.g. `"{0,-20-}"` (and `"{0,|20}"` and `"{0,20|}"` as alternatives for left and right alignment?). 

What do you think?

[Stringier.zip](https://github.com/Entomy/Stringier/files/3988267/Stringier.zip)

**Comment by Entomy** [comment]
Put your code in a PR so I can look at it in full context with the various analyzers. This may still be useful, and I'd like to have its performance benchmarked. If your approach can offer novel features, better performance, or improved saftey it will definately be merged.

However,

This won't be able to do what I'm describing here because of "and automatically adjust width based on column maximums.".

The issue here is something that requires a data structure to solve. Essentially buffering each `Format()` until the end. Consider a simple `Format({0}|{1}|{2})` being used to construct a table. Any individual line will be formatted just fine. However the end of even some trivial calls can result in something like:

| one | two | three |
| eleven | twelve | thirteen |

Which obviously is not a well formatted table. Now obviously if you know the maximal column width for all the data you can put this value in. However for many data sets which may rapidly change, or data with is provided or computed from human input, this becomes impossible and needs to be computed.

**Comment by Entomy** [comment]
@HugoRoss ?
